#' Get Analysis Hub Codes
#'
#' Copy the code after ## Not Run in the Examples below and paste it into a new R Script and save the file as AnalysisHub.R
#' You can then use this R script to run all of your analyses for this course.
#' 
#' @export
#' 
#' @examples
#' \dontrun{
#' getcodes()
#' }
getcodes = function(){
  
clear_console()

  cat("##########################################################\n")
  cat("#                     Analysis Hub                       #\n")
  cat("##########################################################\n")
  cat("#    R Codes for Marketing Analytics                     #\n")
  cat("#    Author: Moein Khanlari, PhD                         #\n")
  cat("#    Version 1.2                                         #\n")
  cat("#    Copyright 2021, Moein Khanlari All rights reserved. #\n")
  cat("#    The listentodata R package and this accompanying    #\n")
  cat("#    R Script are provided to the students at the        #\n")
  cat("#    University of New Hampshire on an 'AS IS' BASIS,    #\n")
  cat("#    WITH ABSOLUTELY NO WARRANTIES either expressed or   #\n")
  cat("#    implied. The package and this script may not be     #\n")
  cat("#    redistributed in whole or part without the express  #\n")
  cat("#    written permission of the author.                   #\n")
  cat("##########################################################\n")
  cat("###################   Attention    #######################\n")
  cat("# This R script allows you to run all of the analyses    #\n")
  cat("# taught in mktg763. The data required for each analysis #\n")
  cat("# must be prepared as taught in this course for these    #\n")
  cat("# scripts to function without error.                     # \n")
  cat("##########################################################\n")
  
  
  cat("# -------    Setup / Update listentodata package -------\n")
  cat("# Running the next lines of code in R will re-install/update\n")
  cat("# your listentodata package and then load it so you can use it.\n")
  cat("# Run these lines of codes one line at a time.\n")
  cat("# Wait until the red stop sign at the top left of the Console\n")
  cat("# disappears before you run the next line.\n")
  cat("# Pay attention to the messages you will get in the Console below.\n")
  cat("# If you get a message that some packages need to be updated,\n")
  cat("# FIRST CLICK IN THE CONSOLE BELOW. Then press Enter/Return \n")
  cat("# to skip those extra updates. You can also choose to update all.\n")
  cat("# The getcodes() function will give you the codes for Analysis_Hub.R\n")
  cat("# Get the next set of instructions at the bottom of the Console.\n")
  cat("\n")
  cat("if (!require(devtools)) install.packages('devtools', dependencies = TRUE)\n")
  cat("suppressWarnings(if (require('listentodata')) remove.packages('listentodata'))\n")
  cat("suppressWarnings(detach(\"package:listentodata\", unload=TRUE))\n")
  cat("devtools::install_github('1moein/listentodata', force=TRUE, dependencies=TRUE)\n")
  cat("listentodata::getcodes()\n")
  cat("# ---------------------------------------------------\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--           Working with Functions               --\n")
  cat("#**************************************************** \n")
  cat("# To use the functions in the listentodata package, \n")
  cat("# we first need to load it by running the next line:\n")
  cat("library(listentodata)\n")
  cat("\n")
  cat("# To get some tips on using functions, run the next line and check out the Console\n")
  cat("tips()\n")
  cat("# To get the latest copy of this script run this line:\n")
  cat("listentodata::getcodes()\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--          0. Practice with easyart             --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# We will practice using this function in the classroom.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?easyart\n")
  cat("clear_console() \n")
  cat("\n")
  cat("select_folder()\n")
  cat("mycolor ='darkblue'\n")
  cat("n = 10\n")
  cat("easyart(n, mycolor)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--      1. Segmentation and Targeting            --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your segmentation\n")
  cat("# data and a second CSV file for your targeting data.\n")
  cat("# Make sure you select the right file by paying attention\n")
  cat("# to the variable name the load_csv_data() is being \n")
  cat("# assigned to.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_SegmentTarget\n")
  cat("clear_console()\n")
  cat("segmentation_data = load_csv_data()\n")
  cat("targeting_data = load_csv_data()\n")
  cat("segments = 3\n")
  cat("Run_SegmentTarget(segmentation_data,targeting_data,segments)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--                2. RFM Analysis                --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have a CSV data file that includes \n")
  cat("# three columns called Recency, Frequency, and Monetary\n")
  cat("# respectively containing numeric values for R, F, and M.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_RFM_Analysis\n")
  cat("clear_console()\n")
  cat("df = load_csv_data()\n")
  cat("Run_RFM_Analysis(df)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--            3. Positioning Analysis            --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your perceptions\n")
  cat("# data and a second CSV file for your preferences data.\n")
  cat("# Make sure you select the right file by paying attention\n")
  cat("# to the variable name the load_csv_data() is being\n")
  cat("# assigned to.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Positioning_Analysis\n")
  cat("clear_console()\n")
  cat("perceptions_data = load_csv_data()\n")
  cat("preferences_data = load_csv_data()\n")
  cat("Run_Positioning_Analysis(perceptions_data,preferences_data)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--              4. CLV Analysis                  --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your profit\n")
  cat("# groups data and a second CSV file for your transition\n")
  cat("# matrix data.\n")
  cat("# Make sure you select the right file by paying attention\n")
  cat("# to the variable name the load_csv_data() is being \n")
  cat("# assigned to.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_CLV_Analysis\n")
  cat("clear_console()\n")
  cat("profitgroups_data = load_csv_data()\n")
  cat("transitionmatrix_data = load_csv_data()\n")
  cat("discount_rate = 0.15\n")
  cat("new_customers = 0\n")
  cat("more_customers = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0)\n")
  cat("resizepaper = 1.2\n")
  cat("Run_CLV_Analysis(profitgroups_data,\n")
  cat("                 transitionmatrix_data,\n")
  cat("                 discount_rate,\n")
  cat("                 new_customers,\n")
  cat("                 more_customers,\n")
  cat("                 resizepaper)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--            5. Optimal Pricing                 --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your pricing\n")
  cat("# survey data. You also need to specify the tested prices\n")
  cat("# in the prices vector. Unless you need to, do not \n")
  cat("# change the values of the three remaining parameters.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Optimal_Pricing\n")
  cat("survey_data = load_csv_data()\n")
  cat("prices = c(1.99,3.99,7.99,10.99,15.99,21.99,26.99)\n")
  cat("probabilities = c(0, 0, 0, 0.2, 0.5)\n")
  cat("marketsize = 10000\n")
  cat("resizepaper = 1.2\n")
  cat("Run_Optimal_Pricing(survey_data,\n")
  cat("                    prices,\n")
  cat("                    probabilities,\n")
  cat("                    marketsize,\n")
  cat("                    resizepaper)\n")
  cat("\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--         6. Regression Analysis                --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your regression\n")
  cat("# data. You also need to specify the formula in myformula.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Regression\n")
  cat("clear_console()\n")
  cat("mydata = load_csv_data()\n")
  cat("head(mydata)\n")
  cat("str(mydata)\n")
  cat("myformula = 'Sales ~ .'\n")
  cat("Run_Regression(mydata, myformula)\n")
  cat("# If you have data for prediction:\n")
  cat("prediction_data = load_csv_data()\n")
  cat("Run_Regression(mydata, myformula, prediction_data)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--       7. Logistic Regression Analysis         --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one CSV data file for your logistic\n")
  cat("# regression data.\n")
  cat("# You also need to specify the formula in myformula.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Logistic\n")
  cat("clear_console()\n")
  cat("mydata = load_csv_data()\n")
  cat("head(mydata)\n")
  cat("str(mydata)\n")
  cat("myformula = 'visited ~ .'\n")
  cat("Run_Logistic(mydata, myformula)\n")
  cat("# If you have data for prediction:\n")
  cat("prediction_data = load_csv_data()\n")
  cat("Run_Logistic(mydata, myformula, prediction_data)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--         8. Sentiment Analysis                   --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You need to have one csv file containing one columne of text.\n")
  cat("# Each cell in this column will be a tweet, review, or document... (No column names/headers)\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Sentiment_Analysis\n")
  cat("clear_console()\n")
  cat("mydata = load_csv_data()\n")
  cat("words2remove = c(\"toremvoe1\", \"toremove2\")\n")
  cat("stemthis = FALSE\n")
  cat("wcmf = 5 #Word Cloud Minimum Frequency: default = 5\n")
  cat("mostfrequent = 25\n")
  cat("Run_Sentiment_Analysis(mydata, stemthis, wcmf, mostfrequent)\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--         9. Conjoint Study Design              --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# You only need to specify the design parameters and \n")
  cat("# their attributes here. The profiles design will be\n")
  cat("# displayed in the Console and also saved in a csv \n")
  cat("# file in the folder you will select.\n")
  cat("# The next few lines prepare and run the analysis. \n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Conjoint_Study_Design\n")
  cat("clear_console()\n")
  cat("# Run the next line to select the folder where results will be saved.\n")
  cat("select_folder()\n")
  cat("designparameters = list(\n")
  cat("    NameOfAttribute1 = c('$100','$200','$300','500'),\n")
  cat("    NameOfAttribute2 = c('A','B','C','D','E'),\n")
  cat("    NameOfAttribute3 = c('Low','Medium','High'),\n")
  cat("    NameOfAttribute4 = c('Yes','No'),\n")
  cat("    NameOfAttribute5 = c('option1', 'option2', 'option3', 'option4'),\n")
  cat("    NameOfAttribute6 = c('option11', 'option22', 'option33', 'option44')\n")
  cat("  \n")
  cat(")\n")
  cat("Run_Conjoint_Study_Design(designparameters)  \n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#****************************************************\n")
  cat("#--            10.  Conjoint Analysis              --\n")
  cat("#**************************************************** \n")
  cat("\n")
  cat("# This analysis requires multiple data files. \n")
  cat("# You also need to specify the formula in myformula.\n")
  cat("# The next few lines allow you to analyze the provided\n")
  cat("# tablet design data.\n")
  cat("\n")
  cat("library(listentodata)\n")
  cat("# Run the next line to get function details in the Help panel\n")
  cat("?Run_Conjoint_Analysis\n")
  cat("clear_console()\n")
  cat("select_folder()  #Select the folder where your data files are\n")
  cat("design = read.csv('Tablet_levels_attributes.csv', na.strings=c('','NA')) #design table\n")
  cat("products = read.csv('Tablet_survey_products.csv')    # READ PRODUCT PROFILES DATA\n")
  cat("ratings =  read.csv('Tablet_survey_ratings.csv')    # READ RATINGS DATA\n")
  cat("alternatives = read.csv('Tablet_New_Product_Alternatives.csv') # Load New product alternative\n")
  cat("competitors = read.csv('Tablet_competitors.csv')  # Load competitors products\n")
  cat("resizepaper = 1\n")
  cat("Run_Conjoint_Analysis(design,\n")
  cat("                      products,\n")
  cat("                      ratings,\n")
  cat("                      alternatives,\n")
  cat("                      competitors,\n")
  cat("                      resizepaper)\n")
  cat("\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("# To analyze data sets from other projects,\n")
  cat("# use these lines that allow you to load your data sets.\n")
  cat("\n")
  cat("library(listentodata)\n")
  cat("clear_console()\n")
  cat("design = load_csv_data()\n")
  cat("products = load_csv_data()\n")
  cat("ratings =  load_csv_data()\n")
  cat("alternatives = load_csv_data()\n")
  cat("competitors = load_csv_data()\n")
  cat("resizepaper = 1\n")
  cat("Run_Conjoint_Analysis(design,\n")
  cat("                      products,\n")
  cat("                      ratings,\n")
  cat("                      alternatives,\n")
  cat("                      competitors,\n")
  cat("                      resizepaper)\n")
  cat("\n")
  cat("\n")
  cat("print('Analysis Complete!')\n")
  cat("\n")
  cat("\n")
  cat("# ============================================================\n")
  cat("#                             Attention!               \n")
  cat("# ============================================================\n")
  cat("# Right Click in this panel, then click Select All\n")
  cat("# This will select everything here, including these instructions.\n")
  cat("# Then, Right Click any where on the selected text and then click Copy\n")
  cat("# Create a new R Script by going to File > New File > R Script \n")
  cat("# Right click in the blank Editor panel that pops up and click Paste\n")
  cat("# Go to File > Save as, and save the script as Analysis_Hub.R\n")
  cat("# All our RStudio analyses will be carried out from within Analysis_Hub.R\n")

  
  
  
   
}