#' Get Analysis Hub Codes
#'
#' Copy the code after ## Not Run in the Examples below and paste it into a new R Script and save the file as AnalysisHub.R
#' You can then use this R script to run all of your analyses for this course.
#' 
#' @export
#' 
#' @examples
#' \dontrun{
#' getdashboard()
#' }
getdashboard = function(){
  
  clear_console()
  
  cat("#################################################\n")
  cat("#                    DASHBOARD                  #\n")
  cat("#################################################\n")
  cat("# R Codes for Marketing Analytics, Version 1.2  #\n")
  cat("# Author: Moein Khanlari, PhD                   #\n")
  cat("# Copyright 2022, Moein Khanlari. All rights    #\n")
  cat("# reserved. The listentodata R package and this #\n")
  cat("# Script are provided to the students at UNH    #\n")
  cat("# on an 'AS IS' BASIS, WITH ABSOLUTELY NO       #\n")
  cat("# WARRANTIES either expressed or implied.       #\n")
  cat("# The package and the script may not be         #\n")
  cat("# redistributed in whole or part without        #\n")
  cat("# the express written permission of the author. #\n")
  cat("# The codes work when the data are prepared     #\n")
  cat("# exactly as taught in this course.             #\n")
  cat("#################################################\n")
  cat("\n")
  cat("library(listentodata) # ALWAYS RUN THIS LINE FIRST\n")
  cat("\n")
  cat("# Run one of the lines to get the code template\n")
  cat("?Run_SegmentTarget\n")
  cat("?Run_Positioning_Analysis\n")
  cat("?Run_RFM_Analysis\n")
  cat("?Run_CLV_Analysis\n")
  cat("?Run_Optimal_Pricing\n")
  cat("?Run_Regression\n")
  cat("?Run_Logistic\n")
  cat("?Run_Conjoint_Analysis\n")
  cat("?Run_Conjoint_Study_Design\n")
  cat("?Run_Sentiment_Analysis\n")
  cat("\n")
  cat("########    BEGIN New Analysis     ########    \n")
  cat("# Paste your sample code here and adapt it.\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("print('Curser catcher: No need to run this line!')\n")
  cat("########    END New Analysis       ########    \n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("\n")
  cat("#################################################\n")
  cat("#         Setup / Update listentodata           #\n")
  cat("#################################################\n")
  cat("# Running the next lines will re-install/update #\n")
  cat("# your listentodata package and then load it.   #\n")
  cat("# If you get a message in the Console to update #\n")
  cat("# packages, FIRST CLICK IN THE CONSOLE.         #\n")
  cat("# Then press Enter/Return to skip the updates.  #\n")
  cat("# Or type the required number to do the updates.#\n")
  cat("#################################################\n")
  cat("\n")
  cat("# Run the next few lines to install/update listentodata package:\n")
  cat("if(!'devtools' %in% rownames(installed.packages())) install.packages('devtools', dependencies = TRUE)\n")
  cat("if('listentodata' %in% (.packages())) detach('package:listentodata', unload=TRUE)\n")
  cat("suppressMessages(if('listentodata' %in% rownames(installed.packages())) remove.packages('listentodata'))\n")
  cat("devtools::install_github('1moein/listentodata', force=TRUE, quiet=TRUE, dependencies=TRUE)\n")
  cat("library(listentodata)\n")
  cat("\n")
  cat("\n")
  cat("#############################\n")
  cat("#          EXTRAS           #\n")
  cat("#############################\n")
  cat("# Some tips in the Console: \n")
  cat("listentodata::tips()\n")
  cat("\n")
  cat("# Practice with easyart()\n")
  cat("library(listentodata)\n")
  cat("?easyart\n")
  cat("\n")
  cat("# Get this dashboard\n")
  cat("getdashboard()\n")
  

}